library(rpart)
args <- commandArgs(TRUE)
train1 <-read.csv(file = args[1],header = TRUE,sep = ",")
test1 <- read.csv(file = args[2],header = TRUE,sep = ",")
validate1 <- read.csv(file = args[3],header = TRUE,sep = ",")
train2 <-read.csv(file = args[4],header = TRUE,sep = ",")
test2 <- read.csv(file = args[5],header = TRUE,sep = ",")
validate2 <- read.csv(file = args[6],header = TRUE,sep = ",")
part1 <- factor(train1$Class)
cfit1 <- rpart(part1~., data = train1, method = 'class', parms = list(split = 'information'),
               minsplit = 2, minbucket = 1)
print(cfit1)
printcp(cfit1)
plot(cfit1)
text(cfit1)
plotcp(cfit1)
text(cfit1)
summary(cfit1)
prune(cfit1, cp = cfit1$cptable[which.min(cfit1$cptable[,"xerror"]),"CP"])
print(cfit1)
plot(cfit1)
text(cfit1)
summary(cfit1)
fit1 <- rpart(Class~., data= test1, method = 'class', parms = list(split = 'information'),
              minsplit = 2, minbucket = 1)
fit1
table(predict(fit1, test1, type = "class"), test1[,"Class"])
print(fit1)
plot(fit1)
text(fit1)
summary(fit1)
vfit1 <- rpart(Class~., data= validate1, method = 'class', parms = list(split = 'information'),
               minsplit = 2, minbucket = 1)
vfit1
table(predict(vfit1, validate1, type = "class"), validate1[,"Class"])
print(vfit1)
plot(vfit1)
text(vfit1)
summary(vfit1)

part2 <- factor(train2$Class)
cfit2 <- rpart(part2~., data = train2, method = 'class', parms = list(split = 'information'),
               minsplit = 2, minbucket = 1)
print(cfit2)
plot(cfit2)
text(cfit2)
plotcp(cfit2)
text(cfit2)
summary(cfit2)
prune(cfit2, cp = cfit2$cptable[which.min(cfit2$cptable[,"xerror"]),"CP"])
print(cfit2)
plot(cfit2)
text(cfit2)
plotcp(cfit2)
text(cfit2)
summary(cfit2)
fit2 <- rpart(Class~., data= test2, method = 'class', parms = list(split = 'information'),
              minsplit = 2, minbucket = 1)
fit2
table(predict(fit2, test2, type = "class"), test2[,"Class"])
print(fit2)
plot(fit2)
text(fit2)
summary(fit2)
vfit2 <- rpart(Class~., data= validate2, method = 'class', parms = list(split = 'information'),
               minsplit = 2, minbucket = 1)
vfit2
table(predict(vfit2, validate2, type = "class"), validate2[,"Class"])
print(vfit2)
plot(vfit2)
text(vfit2)
summary(vfit2)
